### ISSUE TITLE
Big snails become small

### ISSUE THREAD

**Issue by Cleetchle** [LambdAurora/lovely_snails#14]
![2023-06-24_20 32 53](https://github.com/LambdAurora/lovely_snails/assets/137660690/7e91cb84-8b80-4faa-b778-58bce17932eb)

Big snails become small again, even if they have carpets and saddles on them. You also cant remove chests put on the snails when they become small again.

**Comment by LambdAurora** [comment]
Any additional details? In my original testing I couldn't get this.

**Comment by Cleetchle** [comment]
> Any additional details? In my original testing I couldn't get this.


Yes, I was able to replicate the bug by just flying away until the snail is out of render view. After that it becomes small again forever. I am using the latest versions of fabric, fabric api, mod menu, and your mod lovely snails. I hope this helps!

https://github.com/LambdAurora/lovely_snails/assets/137660690/2972f142-6891-4029-8476-ec9d17b9b7cf

**Comment by cnmhqwerty** [comment]
I have this same issue currently by also leaving render distance and coming back, using fabric 1.20
