### ISSUE TITLE
Auto growth?

### ISSUE THREAD

**Issue by VoidLock92** [LambdAurora/lovely_snails#3]
Should the snails grow up on their own to large state? I see many snails that are full grown wandering about, I thought they needed to be cared for to grow large?

**Comment by LambdAurora** [comment]
They should never grow up on their own, if they do it's a bug. In all of my extensive testing I was never able to notice such behavior.

Please check if they are tamed and their satisfaction level in NBT.

**Comment by VoidLock92** [comment]
Hmm seemed to be an issue with an old world having it installed I tested on a new world and spawned a ton of them. They dont seem to be reacting the same way now. Strange.
